<?php

namespace Proxies\__CG__\GestionAdministrative\LgmBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Soutenance extends \GestionAdministrative\LgmBundle\Entity\Soutenance implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'id', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'dateSout', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'mention', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'jury', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'created', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'updated', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'deletedAt');
        }

        return array('__isInitialized__', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'id', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'dateSout', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'mention', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'jury', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'created', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'updated', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\Soutenance' . "\0" . 'deletedAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Soutenance $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSout($dateSout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSout', array($dateSout));

        return parent::setDateSout($dateSout);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSout', array());

        return parent::getDateSout();
    }

    /**
     * {@inheritDoc}
     */
    public function setMention($mention)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMention', array($mention));

        return parent::setMention($mention);
    }

    /**
     * {@inheritDoc}
     */
    public function getMention()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMention', array());

        return parent::getMention();
    }

    /**
     * {@inheritDoc}
     */
    public function setJury($jury)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJury', array($jury));

        return parent::setJury($jury);
    }

    /**
     * {@inheritDoc}
     */
    public function getJury()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJury', array());

        return parent::getJury();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', array($deletedAt));

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', array());

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
