<?php

namespace Proxies\__CG__\GestionAdministrative\LgmBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductionScientifique extends \GestionAdministrative\LgmBundle\Entity\ProductionScientifique implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'id', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'title', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'type', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'datePublication', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'auteur', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'nbAuteur', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'nomJournal', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'nomCongres', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'edition', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'isbn', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'indexe', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'indexFactor', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'created', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'Media', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'updated', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'deletedAt');
        }

        return array('__isInitialized__', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'id', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'title', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'type', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'datePublication', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'auteur', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'nbAuteur', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'nomJournal', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'nomCongres', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'edition', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'isbn', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'indexe', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'indexFactor', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'created', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'Media', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'updated', '' . "\0" . 'GestionAdministrative\\LgmBundle\\Entity\\ProductionScientifique' . "\0" . 'deletedAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProductionScientifique $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePublication($datePublication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePublication', array($datePublication));

        return parent::setDatePublication($datePublication);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePublication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePublication', array());

        return parent::getDatePublication();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuteur($auteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuteur', array($auteur));

        return parent::setAuteur($auteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuteur', array());

        return parent::getAuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbAuteur($nbAuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbAuteur', array($nbAuteur));

        return parent::setNbAuteur($nbAuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbAuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbAuteur', array());

        return parent::getNbAuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomJournal($nomJournal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomJournal', array($nomJournal));

        return parent::setNomJournal($nomJournal);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomJournal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomJournal', array());

        return parent::getNomJournal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCongres($nomCongres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCongres', array($nomCongres));

        return parent::setNomCongres($nomCongres);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCongres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCongres', array());

        return parent::getNomCongres();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdition($edition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdition', array($edition));

        return parent::setEdition($edition);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdition', array());

        return parent::getEdition();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsbn($isbn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsbn', array($isbn));

        return parent::setIsbn($isbn);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsbn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsbn', array());

        return parent::getIsbn();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexe($indexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexe', array($indexe));

        return parent::setIndexe($indexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexe', array());

        return parent::getIndexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndexFactor($indexFactor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndexFactor', array($indexFactor));

        return parent::setIndexFactor($indexFactor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexFactor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexFactor', array());

        return parent::getIndexFactor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', array($deletedAt));

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function addMedia(\GestionAdministrative\LgmBundle\Entity\Media $media)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedia', array($media));

        return parent::addMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMedia(\GestionAdministrative\LgmBundle\Entity\Media $media)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMedia', array($media));

        return parent::removeMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedia', array());

        return parent::getMedia();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', array());

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
