productionscientifique_index:
    path:     /
    defaults: { _controller: "LgmBundle:ProductionScientifique:index" }
    methods:  GET

productionscientifique_show:
    path:     /{id}/show
    defaults: { _controller: "LgmBundle:ProductionScientifique:show" }
    methods:  GET

productionscientifique_new:
    path:     /new
    defaults: { _controller: "LgmBundle:ProductionScientifique:new" }
    methods:  [GET, POST]

productionscientifique_edit:
    path:     /{id}/edit
    defaults: { _controller: "LgmBundle:ProductionScientifique:edit" }
    methods:  [GET, POST]

productionscientifique_delete:
    path:     /{id}/delete
    defaults: { _controller: "LgmBundle:ProductionScientifique:delete" }
    methods:  DELETE
