these_index:
    path:     /
    defaults: { _controller: "LgmBundle:These:index" }
    methods:  GET

these_show:
    path:     /{id}/show
    defaults: { _controller: "LgmBundle:These:show" }
    methods:  GET

these_new:
    path:     /new
    defaults: { _controller: "LgmBundle:These:new" }
    methods:  [GET, POST]

these_edit:
    path:     /{id}/edit
    defaults: { _controller: "LgmBundle:These:edit" }
    methods:  [GET, POST]

these_delete:
    path:     /{id}/delete
    defaults: { _controller: "LgmBundle:These:delete" }
    methods:  DELETE
