<?php

namespace GestionAdministrative\LgmBundle\Repository;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepository extends \Doctrine\ORM\EntityRepository
{
}
