<?php

namespace GestionAdministrative\LgmBundle\Repository;

/**
 * ChercheursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChercheursRepository extends \Doctrine\ORM\EntityRepository
{
}
