<?php

namespace GestionAdministrative\LgmBundle\Repository;

/**
 * chercheursJuniorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chercheursJuniorRepository extends \Doctrine\ORM\EntityRepository
{
}
