<?php

namespace GestionAdministrative\LgmBundle\Repository;

/**
 * chercheursSeniorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chercheursSeniorRepository extends \Doctrine\ORM\EntityRepository
{
}
