<?php

namespace GestionAdministrative\LgmBundle\Repository;

/**
 * communicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class communicationRepository extends \Doctrine\ORM\EntityRepository
{
}
