<?php

namespace GestionAdministrative\LgmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Enseignant_ChercheurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Enseignant_ChercheurRepository extends EntityRepository
{
}
