<?php

namespace GestionAdministrative\LgmBundle\Repository;

/**
 * EquipeRechercheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRechercheRepository extends \Doctrine\ORM\EntityRepository
{
}
