<?php

namespace GestionAdministrative\LgmBundle\Repository;

/**
 * MastereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MastereRepository extends \Doctrine\ORM\EntityRepository
{
}
