<?php

namespace GestionAdministrative\LgmBundle\Repository;

/**
 * ouvrageScientifiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ouvrageScientifiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
