<?php

namespace GestionAdministrative\LgmBundle\Repository;

/**
 * ProductionScientifiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionScientifiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
