<?php

namespace GestionAdministrative\LgmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResearchTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResearchTeamRepository extends EntityRepository
{
}
