<?php

namespace GestionAdministrative\LgmBundle\Repository;

/**
 * TheseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TheseRepository extends \Doctrine\ORM\EntityRepository
{
}
