<?php

namespace GestionAdministrative\LgmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TheseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TheseRepository extends EntityRepository
{
}
